spring:
  application:
    name: marketing
  datasource:
    name: hbdbdevl
    url: jdbc:oracle:thin:@192.168.13.5:6006/hbdbdevl
    username: hbbldevl
    password: hbbldevl
  rabbitmq:
    addresses: rabbitmq-server
    username: guest
    password: guest
server:
  port: 8080
  #context-path: /marketing